import { AlertTriangleIcon, QuoteIcon, XIcon } from "lucide-react";
import { useState } from "react";
import { Badge, Button, Card, SectionHeader, cx } from "@/components/meridian";

type ViewType = "question" | "segment" | "theme" | "contradiction" | "limitation";
export type AnalysisFinding = { id: string; viewType: ViewType; title: string; narrative: string; strength: "emerging" | "supported" | "strong"; supportingEvidenceIds: string[]; conflictingEvidenceIds: string[]; segment?: string };
export type EvidenceDetail = { id: string; channel: "form" | "voice"; excerpt: string; answerLocator?: string; participantName?: string; questionLabel?: string };

export function AnalysisPage({ analysis, findings, evidence, selectedEvidenceId, onOpenEvidence, onCloseEvidence, onStartAnalysis, busy = false }: { analysis?: { id: string; snapshotKind?: "provisional" | "final"; status: string; summary?: string; evidenceCount: number } | null; findings: AnalysisFinding[]; evidence?: EvidenceDetail | null; selectedEvidenceId?: string; onOpenEvidence: (id: string) => void; onCloseEvidence: () => void; onStartAnalysis: () => void; busy?: boolean }) {
  const [view, setView] = useState<ViewType>("theme");
  const visible = findings.filter((finding) => finding.viewType === view);
  return <div className="relative mx-auto w-full max-w-7xl">
    <div className="flex flex-wrap items-end justify-between gap-4"><SectionHeader eyebrow="Evidence synthesis" title="Analysis" description="Every claim stays connected to the participant response that supports—or challenges—it." /><Button onClick={onStartAnalysis} disabled={busy}>{busy ? "Analyzing…" : analysis ? "Refresh snapshot" : "Start analysis"}</Button></div>
    {analysis ? <Card className="mt-6 border-l-2 border-l-[var(--accent-active)] p-5"><div className="flex flex-wrap items-center gap-2"><Badge tone={analysis.snapshotKind === "provisional" ? "warning" : "success"}>{analysis.snapshotKind === "provisional" ? "Provisional snapshot" : "Final snapshot"}</Badge><span className="[font:var(--text-caption)] text-[var(--text-muted)]">{analysis.evidenceCount} response excerpts</span></div><p className="mt-3 max-w-4xl [font:var(--text-body)] text-[var(--text-secondary)]">{analysis.summary ?? (analysis.status === "running" ? "Analysis is in progress." : "No summary is available.")}</p>{analysis.snapshotKind === "provisional" ? <p className="mt-3 flex items-center gap-2 [font:var(--text-body-sm)] text-[var(--status-warning)]"><AlertTriangleIcon className="size-4" />Fieldwork is still running. Refresh after responses close for the final snapshot.</p> : null}</Card> : null}
    <div className="mt-6 flex overflow-x-auto border-b border-[var(--border-default)]" role="tablist">{(["question", "segment", "theme", "contradiction", "limitation"] as ViewType[]).map((item) => <button key={item} type="button" role="tab" aria-selected={view === item} onClick={() => setView(item)} className={cx("border-b-2 px-4 py-3 [font:var(--text-body-sm)] font-semibold capitalize", view === item ? "border-[var(--accent-active)] text-[var(--text-heading)]" : "border-transparent text-[var(--text-muted)] hover:text-[var(--text-heading)]")}>{item}</button>)}</div>
    <div className="mt-5 grid gap-4">{visible.map((finding) => <Card key={finding.id} className="p-5"><div className="flex items-start justify-between gap-4"><div><Badge>{finding.strength}</Badge><h2 className="mt-2 [font:var(--text-heading-sm)] text-[var(--text-heading)]">{finding.title}</h2><p className="mt-2 [font:var(--text-body)] text-[var(--text-secondary)]">{finding.narrative}</p></div>{finding.segment ? <span className="[font:var(--text-caption)] text-[var(--text-muted)]">{finding.segment}</span> : null}</div><div className="mt-4 flex flex-wrap gap-2">{finding.supportingEvidenceIds.map((id, index) => <button key={id} type="button" aria-label={`Supporting evidence ${index + 1}`} onClick={() => onOpenEvidence(id)} className="inline-flex min-h-8 items-center gap-2 border border-[var(--border-default)] bg-[var(--surface-card)] px-2.5 [font:var(--text-caption)] font-semibold text-[var(--text-link)] hover:border-[var(--accent)]"><QuoteIcon className="size-3.5" />Evidence {index + 1}</button>)}{finding.conflictingEvidenceIds.map((id, index) => <button key={id} type="button" aria-label={`Conflicting evidence ${index + 1}`} onClick={() => onOpenEvidence(id)} className="inline-flex min-h-8 items-center gap-2 border border-[var(--status-warning)] px-2.5 [font:var(--text-caption)] font-semibold text-[var(--status-warning)]"><AlertTriangleIcon className="size-3.5" />Conflict {index + 1}</button>)}</div></Card>)}{analysis && visible.length === 0 ? <p className="py-10 text-center [font:var(--text-body)] text-[var(--text-muted)]">No {view} findings in this snapshot.</p> : null}</div>
    {selectedEvidenceId ? <aside role="dialog" aria-label="Evidence detail" className="fixed inset-y-0 right-0 z-50 w-full max-w-md border-l border-[var(--border-default)] bg-[var(--surface-overlay)] shadow-[var(--shadow-lg)]"><div className="flex items-center justify-between border-b border-[var(--border-default)] p-5"><div><p className="[font:var(--text-caption)] uppercase tracking-[var(--tracking-caps)] text-[var(--text-muted)]">Evidence detail</p><h2 className="mt-1 [font:var(--text-heading-sm)] text-[var(--text-heading)]">{evidence?.participantName ?? "Participant response"}</h2></div><button type="button" onClick={onCloseEvidence} aria-label="Close evidence"><XIcon className="size-5" /></button></div><div className="p-6">{evidence ? <><div className="flex gap-2"><Badge tone="info">{evidence.channel === "voice" ? "Voice transcript" : "Typed answer"}</Badge>{evidence.answerLocator ? <span className="font-mono text-xs text-[var(--text-muted)]">{evidence.answerLocator}</span> : null}</div>{evidence.questionLabel ? <p className="mt-6 [font:var(--text-body-sm)] font-semibold text-[var(--text-heading)]">{evidence.questionLabel}</p> : null}<blockquote className="mt-3 border-l-2 border-[var(--accent-active)] pl-4 [font:var(--text-body-lg)] text-[var(--text-heading)]">“{evidence.excerpt}”</blockquote></> : <p className="text-[var(--text-muted)]">Loading exact response…</p>}</div></aside> : null}
  </div>;
}
