import { CheckCircle2Icon, MailIcon, PhoneCallIcon, RotateCcwIcon } from "lucide-react";
import { Badge, Button } from "@/components/meridian";

type Channel = "email" | "voice";
type Batch = { id: string; status: string; participantCount: number; channels: Channel[]; questionnaireVersion: number };
type Participant = { id: string; name: string; segment?: string; status: string; consentStatus: string; channels: Channel[]; deliveryStatus: string; retryDeliveryId?: string };
type Response = { id: string; participantId: string; participantName: string; channel: "form" | "voice"; status: string; occurredAt: number; summary?: string; transcript?: Array<{ role: string; message: string }> };

export function FieldworkPage(props: { batch: Batch | null; participants: Participant[]; responses: Response[]; onApprove: (id: string) => Promise<void>; onLaunch: (id: string) => Promise<void>; onRetry: (id: string) => Promise<void> }) {
  const selected = props.responses[0];
  const completed = props.participants.filter((participant) => participant.status === "completed").length;
  return <div>
    <header className="flex flex-wrap items-end justify-between gap-4">
      <div><p className="[font:var(--text-caption)] uppercase tracking-[var(--tracking-caps)] text-[var(--accent-active)]">Approved outreach control plane</p><h1 className="mt-1 [font:var(--text-heading-sm)] text-[var(--text-heading)]">Fieldwork operations</h1><p className="mt-1 [font:var(--text-body-sm)] text-[var(--text-secondary)]">Approval, consent, provider delivery, and evidence stay on one auditable rail.</p></div>
      {props.batch ? <div className="flex gap-2"><Badge tone="info">{props.batch.status}</Badge>{props.batch.status === "awaiting_approval" ? <Button onClick={() => void props.onApprove(props.batch!.id)}><CheckCircle2Icon className="size-4" />Approve batch</Button> : null}{props.batch.status === "approved" ? <Button onClick={() => void props.onLaunch(props.batch!.id)}>Launch approved batch</Button> : null}</div> : null}
    </header>
    <section aria-label="Fieldwork summary" className="mt-6 grid border border-[var(--border-default)] bg-[var(--surface-card)] sm:grid-cols-4">
      {[['Approved sample', props.batch?.participantCount ?? props.participants.length], ['Completed', completed], ['Responses', props.responses.length], ['Questionnaire', props.batch ? `v${props.batch.questionnaireVersion}` : '—']].map(([label, value]) => <div key={String(label)} className="border-b border-[var(--border-default)] p-4 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="[font:var(--text-caption)] uppercase tracking-[var(--tracking-caps)] text-[var(--text-muted)]">{label}</p><p className="mt-1 [font:var(--text-heading-sm)] text-[var(--text-heading)]">{value}</p></div>)}
    </section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,0.8fr)]">
      <section className="overflow-hidden border border-[var(--border-default)] bg-[var(--surface-card)]"><h2 className="border-b border-[var(--border-default)] px-4 py-3 [font:var(--text-body)] font-semibold">Participant lifecycle</h2>{props.participants.map((participant) => <div key={participant.id} className="grid grid-cols-[minmax(0,1fr)_110px_110px_auto] items-center gap-3 border-b border-[var(--border-default)] px-4 py-3 last:border-0"><div><p className="[font:var(--text-body-sm)] font-semibold">{participant.name}</p><p className="[font:var(--text-caption)] text-[var(--text-muted)]">{participant.segment ?? 'Unassigned'} · consent {participant.consentStatus}</p></div><span className="flex gap-1">{participant.channels.map((channel) => channel === 'email' ? <MailIcon key={channel} className="size-4" /> : <PhoneCallIcon key={channel} className="size-4" />)}</span><Badge tone={participant.status === 'completed' ? 'success' : participant.status === 'failed' ? 'danger' : 'neutral'}>{participant.status}</Badge>{participant.retryDeliveryId ? <Button size="sm" variant="outline" aria-label={`Retry ${participant.name}`} onClick={() => void props.onRetry(participant.retryDeliveryId!)}><RotateCcwIcon className="size-3.5" />Retry</Button> : <span />}</div>)}</section>
      <section className="border border-[var(--border-default)] bg-[var(--surface-card)]"><h2 className="border-b border-[var(--border-default)] px-4 py-3 [font:var(--text-body)] font-semibold">Response detail</h2>{selected ? <article className="p-5"><div className="flex justify-between gap-3"><div><h3 className="[font:var(--text-heading-sm)]">{selected.participantName}</h3><p className="[font:var(--text-caption)] text-[var(--text-muted)]">{selected.channel} · {new Date(selected.occurredAt).toLocaleString()}</p></div><Badge tone="success">{selected.status}</Badge></div><h4 className="mt-6 [font:var(--text-caption)] uppercase tracking-[var(--tracking-caps)] text-[var(--text-muted)]">Summary</h4><p className="mt-2 [font:var(--text-body-sm)] text-[var(--text-secondary)]">{selected.summary ?? 'Summary pending.'}</p><h4 className="mt-6 [font:var(--text-caption)] uppercase tracking-[var(--tracking-caps)] text-[var(--text-muted)]">Transcript</h4><div className="mt-3 space-y-3">{selected.transcript?.map((turn, index) => <div key={`${turn.role}-${index}`}><p className="[font:var(--text-caption)] uppercase text-[var(--text-muted)]">{turn.role}</p><p className="[font:var(--text-body-sm)] text-[var(--text-secondary)]">{turn.message}</p></div>)}</div></article> : <p className="p-5 [font:var(--text-body-sm)] text-[var(--text-muted)]">No responses yet.</p>}</section>
    </div>
  </div>;
}
